import { useState } from 'react';
import { Button, Card, DatePicker, Form, InputNumber, Select, Space, Table, Tag, Typography, message } from 'antd';
import dayjs from 'dayjs';
import { useCaisses, useEquipes, useFermerReleve, useOuvrirReleve, usePompes, useReleves, useVendeurs } from '../hooks/useCarburant';

export function RelevePompes() {
  const [form] = Form.useForm(); const [closeForm] = Form.useForm(); const [messageApi, contextHolder] = message.useMessage(); const [closingId, setClosingId] = useState<number | null>(null);
  const { data: pompes = [] } = usePompes(); const { data: equipes = [] } = useEquipes(); const { data: caisses = [] } = useCaisses(); const { data: vendeurs = [] } = useVendeurs(); const { data: releves = [], isLoading } = useReleves(); const open = useOuvrirReleve(); const close = useFermerReleve();
  const submit = async (values: { date: dayjs.Dayjs; equipeId: number; caisseId: number; pompeId: number; vendeurId: number; indexOuverture: number }) => { const date = values.date.format('YYYY-MM-DD'); const existing = releves.find((releve) => releve.date === date && releve.equipe.id === values.equipeId && releve.caisse.id === values.caisseId && releve.pompe.id === values.pompeId); if (existing) { messageApi.warning(existing.indexFermeture == null ? 'Un relevé ouvert existe déjà pour cette combinaison. Fermez-le depuis l’historique.' : 'Un relevé existe déjà pour cette combinaison.'); return; } try { await open.mutateAsync({ ...values, date }); form.resetFields(); messageApi.success('Releve ouvert.'); } catch (error: any) { messageApi.error(error.response?.data?.message ?? 'Impossible d’ouvrir le relevé.'); } };
  const submitClose = async (values: { indexFermeture: number }) => { if (!closingId) return; try { await close.mutateAsync({ id: closingId, indexFermeture: values.indexFermeture }); closeForm.resetFields(); setClosingId(null); messageApi.success('Releve ferme.'); } catch (error: any) { messageApi.error(error.response?.data?.message ?? 'Impossible de fermer le relevé.'); } };
  const options = (items: { id: number; code?: string; libelle?: string; nom?: string }[]) => items.map((item) => ({ value: item.id, label: item.nom ?? `${item.code} · ${item.libelle}` }));
  return <section className="page-section">{contextHolder}<div className="page-heading"><div><Typography.Text className="eyebrow">CARBURANT / EXPLOITATION</Typography.Text><Typography.Title level={2}>Relevés de pompes</Typography.Title></div><Typography.Text type="secondary">Ouverture et clôture des index par équipe</Typography.Text></div><Card title="Ouvrir un relevé" className="form-card"><Form form={form} layout="vertical" onFinish={submit} initialValues={{ date: dayjs() }}><div className="form-grid"><Form.Item label="Date" name="date" rules={[{ required: true }]}><DatePicker style={{ width: '100%' }} /></Form.Item><Form.Item label="Pompe" name="pompeId" rules={[{ required: true }]}><Select options={options(pompes)} /></Form.Item><Form.Item label="Équipe" name="equipeId" rules={[{ required: true }]}><Select options={options(equipes)} /></Form.Item><Form.Item label="Caisse" name="caisseId" rules={[{ required: true }]}><Select options={options(caisses)} /></Form.Item><Form.Item label="Vendeur" name="vendeurId" rules={[{ required: true }]}><Select options={options(vendeurs)} /></Form.Item><Form.Item label="Index ouverture" name="indexOuverture" rules={[{ required: true }]}><InputNumber min={0} precision={3} style={{ width: '100%' }} /></Form.Item></div><Button type="primary" htmlType="submit" loading={open.isPending}>Ouvrir le relevé</Button></Form></Card><Card title="Historique récent" className="table-card"><Table rowKey="id" loading={isLoading} dataSource={releves} columns={[{ title: 'Date', dataIndex: 'date' }, { title: 'Pompe', dataIndex: ['pompe', 'libelle'] }, { title: 'Équipe', dataIndex: ['equipe', 'libelle'] }, { title: 'Ouverture', dataIndex: 'indexOuverture', render: (value) => value.toFixed(3) }, { title: 'Fermeture', dataIndex: 'indexFermeture', render: (value, row) => value == null ? closingId === row.id ? <Form form={closeForm} layout="inline" onFinish={submitClose}><Form.Item name="indexFermeture" rules={[{ required: true }]}><InputNumber min={row.indexOuverture} precision={3} /></Form.Item><Button type="primary" htmlType="submit" size="small">Valider</Button><Button size="small" onClick={() => setClosingId(null)}>Annuler</Button></Form> : <Button size="small" onClick={() => setClosingId(row.id)}>Fermer</Button> : <Tag color="green">{value.toFixed(3)}</Tag> }, { title: 'CA', dataIndex: 'ca', render: (value, row) => value == null ? '—' : <Typography.Text strong>{value.toFixed(3)} TND</Typography.Text> }]} /></Card></section>;
}
