import { useState } from 'react';
import { Button, Card, DatePicker, InputNumber, Popconfirm, Select, Space, Table, Tag, Typography, message } from 'antd';
import dayjs from 'dayjs';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import api from '../../../lib/axios';
import { usePermission } from '../../../hooks/usePermission';

export function RetourCuve() {
  const [date, setDate] = useState(dayjs()); const [equipeId, setEquipeId] = useState<number>(); const [caisseId, setCaisseId] = useState<number>(); const [vendeurId, setVendeurId] = useState<number>(); const [volumes, setVolumes] = useState<Record<number, number>>({}); const queryClient = useQueryClient(); const [messageApi, holder] = message.useMessage();
  const allowed = usePermission('gerant'); const { data: pompes = [] } = useQuery({ queryKey: ['pompes'], queryFn: async () => (await api.get('/pompes')).data }); const { data: equipes = [] } = useQuery({ queryKey: ['equipes'], queryFn: async () => (await api.get('/equipes')).data }); const { data: caisses = [] } = useQuery({ queryKey: ['caisses'], queryFn: async () => (await api.get('/caisses')).data }); const { data: vendeurs = [] } = useQuery({ queryKey: ['vendeurs'], queryFn: async () => (await api.get('/vendeurs')).data }); const { data: rows = [] } = useQuery({ queryKey: ['retours'], queryFn: async () => (await api.get('/carburant/retours')).data });
  const create = useMutation({ mutationFn: (input: unknown) => api.post('/carburant/retours', input), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ['retours'] }); messageApi.success('Retour enregistré.'); setVolumes({}); } });
  const validate = useMutation({ mutationFn: (id: number) => api.patch(`/carburant/retours/${id}/valider`), onSuccess: () => queryClient.invalidateQueries({ queryKey: ['retours'] }) });
  const lines = pompes.filter((pump: any) => volumes[pump.id] > 0).map((pump: any) => ({ pompeId: pump.id, volume: volumes[pump.id], tauxTVA: pump.cuve.tauxTVA ?? 0 })); const total = lines.reduce((sum: number, line: any) => sum + line.volume * Number(pompes.find((pump: any) => pump.id === line.pompeId)?.cuve?.prixAchatHT ?? 0), 0);
  return <section className="page-section">{holder}<div className="page-heading"><div><Typography.Text className="eyebrow">CARBURANT / RETOUR</Typography.Text><Typography.Title level={2}>Retour cuve</Typography.Title></div><Space><DatePicker value={date} onChange={(value) => value && setDate(value)} /><Select placeholder="Equipe" options={equipes.map((x: any) => ({ value: x.id, label: x.libelle }))} onChange={setEquipeId} /><Select placeholder="Caisse" options={caisses.map((x: any) => ({ value: x.id, label: x.libelle }))} onChange={setCaisseId} /><Select placeholder="Vendeur" options={vendeurs.map((x: any) => ({ value: x.id, label: x.nom }))} onChange={setVendeurId} /></Space></div><Card><Table rowKey="id" dataSource={pompes} pagination={false} columns={[{ title: 'Pompe', dataIndex: 'libelle' }, { title: 'Cuve', render: (_: unknown, row: any) => row.cuve.libelle }, { title: 'Volume retourné', render: (_: unknown, row: any) => <InputNumber min={0} precision={3} value={volumes[row.id]} onChange={(value) => setVolumes({ ...volumes, [row.id]: value ?? 0 })} /> }]} /><Typography.Title level={4}>Total: {total.toFixed(3)} TND</Typography.Title><Button type="primary" disabled={!equipeId || !caisseId || !vendeurId || !lines.length} loading={create.isPending} onClick={() => create.mutate({ date: date.format('YYYY-MM-DD'), equipeId, caisseId, vendeurId, lignes: lines })}>Enregistrer</Button></Card><Card title="Historique"><Table rowKey="id" dataSource={rows} columns={[{ title: 'Date', dataIndex: 'date' }, { title: 'Volume', dataIndex: 'totalVolume' }, { title: 'Valeur', dataIndex: 'totalValeur' }, { title: 'État', dataIndex: 'valide', render: (value) => <Tag color={value ? 'green' : 'orange'}>{value ? 'Validé' : 'Brouillon'}</Tag> }, { title: 'Action', render: (_: unknown, row: any) => allowed && !row.valide ? <Popconfirm title="Valider ce retour ?" onConfirm={() => validate.mutate(row.id)}><Button size="small" type="primary" loading={validate.isPending}>Valider</Button></Popconfirm> : null }]} /></Card></section>;
}
