import { useState } from 'react';
import dayjs, { type Dayjs } from 'dayjs';
import { Badge, Button, Card, Col, DatePicker, Form, Input, InputNumber, Row, Select, Space, Statistic, Table, Tag, Typography, message } from 'antd';
import { useBanques, useCreateMouvement, useModesPayment, useMouvements, usePositionBanque, useRapprocherMouvement } from '../hooks/useBanque';

const money = (value: number) => `${(value ?? 0).toFixed(3)} TND`;
export function MouvementsBancaires() {
  const [bankId, setBankId] = useState<number>(); const [date, setDate] = useState<Dayjs>(dayjs()); const [form] = Form.useForm(); const [messageApi, holder] = message.useMessage(); const { data: banks = [] } = useBanques(); const { data: modes = [] } = useModesPayment(); const { data: movements = [], isLoading } = useMouvements(bankId); const { data: position } = usePositionBanque(bankId); const create = useCreateMouvement(); const reconcile = useRapprocherMouvement();
  const submit = async (values: { modePaymentId: number; montant: number; dateEcheance?: Dayjs }) => { if (!bankId) { messageApi.warning('Sélectionnez une banque.'); return; } try { await create.mutateAsync({ banqueId: bankId, modePaymentId: values.modePaymentId, montant: values.montant, date: date.format('YYYY-MM-DD'), dateEcheance: values.dateEcheance?.format('YYYY-MM-DD') }); form.resetFields(); messageApi.success('Mouvement enregistré.'); } catch (error: any) { messageApi.error(error?.response?.data?.message ?? 'Erreur d’enregistrement.'); } };
  return <section className="page-section">{holder}<div className="page-heading"><div><Typography.Text className="eyebrow">BANQUE / TRÉSORERIE</Typography.Text><Typography.Title level={2}>Mouvements bancaires</Typography.Title></div><Select allowClear placeholder="Banque" style={{ width: 260 }} value={bankId} onChange={setBankId} options={banks.map((bank) => ({ value: bank.id, label: bank.libelle }))} /></div><Row gutter={[16, 16]} className="stat-row"><Col xs={24} md={8}><Card><Statistic title="Solde total" value={position?.soldeTotal ?? 0} precision={3} suffix="TND" /></Card></Col><Col xs={24} md={8}><Card><Statistic title="Solde rapproché" value={position?.soldeRapproche ?? 0} precision={3} suffix="TND" valueStyle={{ color: '#16803c' }} /></Card></Col><Col xs={24} md={8}><Card><Statistic title="En attente" value={position?.mouvementsEnAttente ?? 0} /></Card></Col></Row><Card title="Nouveau mouvement" className="form-card"><Form form={form} layout="inline" onFinish={submit}><Form.Item name="modePaymentId" rules={[{ required: true }]}><Select placeholder="Mode de paiement" style={{ width: 220 }} options={modes.map((mode) => ({ value: mode.id, label: mode.libelle }))} /></Form.Item><Form.Item name="montant" rules={[{ required: true }]}><InputNumber min={0.001} precision={3} placeholder="Montant" /></Form.Item><Form.Item name="dateEcheance"><DatePicker placeholder="Échéance" /></Form.Item><Button type="primary" htmlType="submit" loading={create.isPending}>Enregistrer</Button></Form></Card><Card title="Historique"><Table rowKey="id" loading={isLoading} dataSource={movements} columns={[{ title: 'Date', dataIndex: 'date' }, { title: 'Banque', dataIndex: ['banque', 'libelle'] }, { title: 'Mode', dataIndex: ['modePayment', 'libelle'] }, { title: 'Montant', dataIndex: 'montant', render: money }, { title: 'Échéance', dataIndex: 'dateEcheance' }, { title: 'Statut', dataIndex: 'rapproche', render: (value) => <Badge status={value ? 'success' : 'processing'} text={value ? 'Rapproché' : 'En attente'} /> }, { title: 'Action', render: (_, record) => record.rapproche ? <Tag color="green">Terminé</Tag> : <Button size="small" onClick={() => reconcile.mutateAsync(record.id)}>Rapprocher</Button> }]} /></Card></section>;
}
