import { useState } from 'react';
import { Button, Form, Input, Modal, Popconfirm, Select, Space, Table, Tag, Typography, message } from 'antd';
import { Navigate } from 'react-router-dom';
import { useAuthStore, type Role } from '../../../lib/auth';
import { usePermission } from '../../../hooks/usePermission';
import { useCreateUtilisateur, useResetUtilisateurPassword, useToggleUtilisateur, useUpdateUtilisateur, useUtilisateurs, type ManagedUser } from '../hooks/useUtilisateurs';

const roleColor: Record<Role, string> = { gerant: 'gold', caissier: 'blue', vendeur: 'default' };
const roleLabel: Record<Role, string> = { gerant: 'Gérant', caissier: 'Caissier', vendeur: 'Vendeur' };
const initial = { nom: '', prenom: '', username: '', telephone: '', role: 'vendeur' as Role, password: '', confirmPassword: '' };
export function GestionUtilisateurs() {
  const allowed = usePermission('gerant'); const current = useAuthStore((state) => state.user); const [editing, setEditing] = useState<ManagedUser>(); const [modal, setModal] = useState<'create' | 'edit' | 'reset' | null>(null); const [selected, setSelected] = useState<ManagedUser>(); const [form] = Form.useForm(); const [messageApi, holder] = message.useMessage(); const { data = [], isLoading } = useUtilisateurs(); const create = useCreateUtilisateur(); const update = useUpdateUtilisateur(); const reset = useResetUtilisateurPassword(); const toggle = useToggleUtilisateur();
  if (!allowed) return <Navigate to="/" replace />;
  const openCreate = () => { setEditing(undefined); setModal('create'); form.setFieldsValue(initial); }; const openEdit = (user: ManagedUser) => { setEditing(user); setModal('edit'); form.setFieldsValue({ ...user, password: undefined, confirmPassword: undefined }); }; const submit = async (values: typeof initial) => { try { if (modal === 'create') { if (values.password !== values.confirmPassword) { form.setFields([{ name: 'confirmPassword', errors: ['Les mots de passe ne correspondent pas.'] }]); return; } await create.mutateAsync(values); } else if (editing) await update.mutateAsync({ id: editing.id, input: { nom: values.nom, prenom: values.prenom, telephone: values.telephone, role: values.role, actif: editing.actif } }); setModal(null); messageApi.success('Utilisateur enregistré.'); } catch (error: any) { messageApi.error(error?.response?.data?.message ?? 'Opération impossible.'); } };
  const toggleUser = async (user: ManagedUser) => { try { await toggle.mutateAsync({ user, actif: !user.actif }); messageApi.success(user.actif ? 'Compte désactivé.' : 'Compte réactivé.'); } catch (error: any) { messageApi.error(error?.response?.data?.message ?? 'Opération impossible.'); } };
  const resetPassword = async (values: { newPassword: string; confirmPassword: string }) => { if (!selected || values.newPassword !== values.confirmPassword) { messageApi.error('Les mots de passe ne correspondent pas.'); return; } try { await reset.mutateAsync({ id: selected.id, newPassword: values.newPassword }); setModal(null); messageApi.success('Mot de passe réinitialisé.'); } catch { messageApi.error('Réinitialisation impossible.'); } };
  return <section className="page-section">{holder}<div className="page-heading"><div><Typography.Text className="eyebrow">SYSTÈME / ACCÈS</Typography.Text><Typography.Title level={2}>Gestion des utilisateurs</Typography.Title></div><Button type="primary" onClick={openCreate}>Nouvel utilisateur</Button></div><Table rowKey="id" loading={isLoading} dataSource={data} columns={[{ title: 'Nom complet', render: (_, user) => `${user.prenom} ${user.nom}` }, { title: 'Username', dataIndex: 'username' }, { title: 'Rôle', dataIndex: 'role', render: (value: Role) => <Tag color={roleColor[value]}>{roleLabel[value]}</Tag> }, { title: 'Statut', dataIndex: 'actif', render: (value) => <Tag color={value ? 'green' : 'red'}>{value ? 'Actif' : 'Inactif'}</Tag> }, { title: 'Dernière connexion', dataIndex: 'lastLoginAt', render: (value) => value ? new Date(value).toLocaleString('fr-FR') : 'Jamais' }, { title: 'Actions', render: (_, user) => <Space><Button size="small" onClick={() => openEdit(user)} disabled={user.id === current?.id}>Modifier</Button><Button size="small" onClick={() => { setSelected(user); setModal('reset'); }} disabled={user.id === current?.id}>Réinitialiser</Button><Popconfirm title={user.actif ? 'Désactiver ce compte ?' : 'Réactiver ce compte ?'} onConfirm={() => toggleUser(user)}><Button size="small" danger={user.actif} disabled={user.id === current?.id}>{user.actif ? 'Désactiver' : 'Réactiver'}</Button></Popconfirm></Space> }]} /><Modal title={modal === 'create' ? 'Nouvel utilisateur' : modal === 'edit' ? 'Modifier utilisateur' : 'Réinitialiser le mot de passe'} open={Boolean(modal)} onCancel={() => setModal(null)} footer={null}>{modal === 'reset' ? <Form layout="vertical" onFinish={resetPassword}><Form.Item name="newPassword" label="Nouveau mot de passe" rules={[{ required: true, min: 6 }]}><Input.Password /></Form.Item><Form.Item name="confirmPassword" label="Confirmation" rules={[{ required: true }]}><Input.Password /></Form.Item><Button type="primary" htmlType="submit">Réinitialiser</Button></Form> : <Form form={form} layout="vertical" onFinish={submit}><Form.Item name="nom" label="Nom" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="prenom" label="Prénom" rules={[{ required: true }]}><Input /></Form.Item><Form.Item name="username" label="Username" rules={[{ required: true }]}><Input disabled={modal === 'edit'} /></Form.Item><Form.Item name="telephone" label="Téléphone"><Input /></Form.Item><Form.Item name="role" label="Rôle"><Select options={Object.entries(roleLabel).map(([value, label]) => ({ value, label }))} /></Form.Item>{modal === 'create' && <><Form.Item name="password" label="Mot de passe" rules={[{ required: true, min: 6 }]}><Input.Password /></Form.Item><Form.Item name="confirmPassword" label="Confirmation" rules={[{ required: true }]}><Input.Password /></Form.Item></>}<Button type="primary" htmlType="submit">Enregistrer</Button></Form>}</Modal></section>;
}
