import { useState } from 'react';
import dayjs, { type Dayjs } from 'dayjs';
import { Button, Card, DatePicker, Form, Input, InputNumber, Select, Space, Typography, message } from 'antd';
import { useFournisseurs, useCreateReglementFournisseur } from '../hooks/useFournisseurs';

export function ReglementFournisseur() {
  const [form] = Form.useForm(); const [date, setDate] = useState<Dayjs>(dayjs()); const [messageApi, holder] = message.useMessage(); const { data: fournisseurs = [] } = useFournisseurs(); const create = useCreateReglementFournisseur();
  const submit = async (values: { fournisseurId: number; montant: number; modePayment: string; echeance?: Dayjs }) => { try { await create.mutateAsync({ fournisseurId: values.fournisseurId, date: date.format('YYYY-MM-DD'), valide: true, lignes: [{ montant: values.montant, modePayment: values.modePayment, echeance: values.echeance?.format('YYYY-MM-DD'), reste: 0 }] }); form.resetFields(); messageApi.success('Règlement fournisseur enregistré.'); } catch (error: any) { messageApi.error(error?.response?.data?.message ?? 'Impossible d’enregistrer le règlement.'); } };
  return <section className="page-section">{holder}<div className="page-heading"><div><Typography.Text className="eyebrow">FOURNISSEURS / RÈGLEMENTS</Typography.Text><Typography.Title level={2}>Règlement fournisseur</Typography.Title></div></div><Card><Form form={form} layout="vertical" onFinish={submit}><Form.Item label="Fournisseur" name="fournisseurId" rules={[{ required: true }]}><Select options={fournisseurs.map((item) => ({ value: item.id, label: item.raisonSociale }))} /></Form.Item><Form.Item label="Date"><DatePicker value={date} onChange={(value) => value && setDate(value)} /></Form.Item><Form.Item label="Montant" name="montant" rules={[{ required: true }]}><InputNumber min={0.001} precision={3} style={{ width: '100%' }} /></Form.Item><Form.Item label="Mode de paiement" name="modePayment" rules={[{ required: true }]}><Input placeholder="Espèces, chèque, virement..." /></Form.Item><Form.Item label="Échéance" name="echeance"><DatePicker /></Form.Item><Button type="primary" htmlType="submit" loading={create.isPending}>Enregistrer le règlement</Button></Form></Card></section>;
}
