import { useState } from 'react';
import dayjs, { type Dayjs } from 'dayjs';
import { Button, Card, DatePicker, Form, InputNumber, Modal, Select, Space, Table, Typography, message } from 'antd';
import { useFournisseurs, useLibRas, useCreateRetenueSource, useRetenuesSource } from '../hooks/useFournisseurs';

const money = (value: number) => `${(value ?? 0).toFixed(3)} TND`;

export function RetenuesSource() {
  const [open, setOpen] = useState(false); const [form] = Form.useForm(); const [date, setDate] = useState<Dayjs>(dayjs()); const [messageApi, holder] = message.useMessage(); const { data: fournisseurs = [] } = useFournisseurs(); const { data: rates = [] } = useLibRas(); const { data: retenues = [], isLoading } = useRetenuesSource(); const create = useCreateRetenueSource();
  const submit = async (values: { fournisseurId: number; codeRet: number; mtBrut: number }) => { const rate = rates.find((item) => item.id === values.codeRet); if (!rate) return; try { await create.mutateAsync({ dateRas: date.format('YYYY-MM-DD'), fournisseurId: values.fournisseurId, valide: true, lignes: [{ codeRet: values.codeRet, mtBrut: values.mtBrut, tauxRetenu: rate.tauxRetenu, fournisseurId: values.fournisseurId, valide: true }] }); setOpen(false); form.resetFields(); messageApi.success('Retenue créée.'); } catch (error: any) { messageApi.error(error?.response?.data?.message ?? 'Impossible de créer la retenue.'); } };
  return <section className="page-section">{holder}<div className="page-heading"><div><Typography.Text className="eyebrow">FOURNISSEURS / FISCALITÉ</Typography.Text><Typography.Title level={2}>Retenues à la source</Typography.Title></div><Button type="primary" onClick={() => setOpen(true)}>Nouvelle retenue</Button></div><Card><Table rowKey="id" loading={isLoading} dataSource={retenues} columns={[{ title: 'Date', dataIndex: 'dateRas' }, { title: 'Fournisseur', dataIndex: ['fournisseur', 'raisonSociale'] }, { title: 'Total brut', dataIndex: 'totalBrut', render: money }, { title: 'Total retenu', dataIndex: 'totalRetenu', render: money }, { title: 'Total net', dataIndex: 'totalNet', render: money }]} /></Card><Modal title="Nouvelle retenue à la source" open={open} onCancel={() => setOpen(false)} footer={null}><Form form={form} layout="vertical" onFinish={submit}><Form.Item label="Date"><DatePicker value={date} onChange={(value) => value && setDate(value)} /></Form.Item><Form.Item name="fournisseurId" label="Fournisseur" rules={[{ required: true }]}><Select options={fournisseurs.map((item) => ({ value: item.id, label: item.raisonSociale }))} /></Form.Item><Form.Item name="codeRet" label="Taux de retenue" rules={[{ required: true }]}><Select options={rates.map((item) => ({ value: item.id, label: `${item.libelle} (${item.tauxRetenu}%)` }))} /></Form.Item><Form.Item name="mtBrut" label="Montant brut" rules={[{ required: true }]}><InputNumber min={0.001} precision={3} style={{ width: '100%' }} /></Form.Item><Button type="primary" htmlType="submit" loading={create.isPending}>Enregistrer</Button></Form></Modal></section>;
}
