export const BUSINESS_RULES = {
  MAX_OPEN_SESSIONS_PER_CAISSE: 1,
  INDEX_FERMETURE_MIN_DELTA: 0,
  INDEX_FERMETURE_MAX_DELTA_LITRES: 50000,
  JAUGEAGE_ALERT_THRESHOLD_LITRES: 100,
  JAUGEAGE_BLOCK_THRESHOLD_LITRES: 500,
  FONDS_CAISSE_TOLERANCE_TND: 1,
  CREDIT_CREATES_RECETTE_LINE: true,
  MAX_RETOUR_CUVE_LITRES_PER_POMPE: 20,
  DEPOT_BANQUE_FORMULA: 'especes - fondsDeCaisseFermeture',
} as const;
