import React from 'react';
import ReactDOM from 'react-dom/client';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { ConfigProvider } from 'antd';
import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom';
import { AppLayout } from './components/AppLayout';
import { ProtectedRoute } from './components/ProtectedRoute';
import { Login } from './modules/auth/pages/Login';
import { RelevePompes } from './modules/carburant/pages/RelevePompes';
import { StockCuves } from './modules/carburant/pages/StockCuves';
import { RetourCuve } from './modules/carburant/pages/RetourCuve';
import { InventaireCarburant } from './modules/carburant/pages/InventaireCarburant';
import { Jaugeages } from './modules/carburant/pages/Jaugeages';
import { SaisieCaisse } from './modules/caisse/pages/SaisieCaisse';
import { ClotureCaisse } from './modules/caisse/pages/ClotureCaisse';
import { ListeClients } from './modules/clients/pages/ListeClients';
import { SaisieBL } from './modules/clients/pages/SaisieBL';
import { ListeFactures } from './modules/clients/pages/ListeFactures';
import { Impayes } from './modules/clients/pages/Impayes';
import { ListeFournisseurs } from './modules/fournisseurs/pages/ListeFournisseurs';
import { ReglementFournisseur } from './modules/fournisseurs/pages/ReglementFournisseur';
import { RetenuesSource } from './modules/fournisseurs/pages/RetenuesSource';
import { AvoirsFournisseurs } from './modules/fournisseurs/pages/AvoirsFournisseurs';
import { MouvementsBancaires } from './modules/banque/pages/MouvementsBancaires';
import { PositionBanque } from './modules/banque/pages/PositionBanque';
import { ListeProduits } from './modules/boutique/pages/ListeProduits';
import { AchatProduits } from './modules/boutique/pages/AchatProduits';
import { Inventaire } from './modules/boutique/pages/Inventaire';
import { VentesResume } from './modules/boutique/pages/VentesResume';
import { Dashboard } from './modules/dashboard/pages/Dashboard';
import { GestionCartes } from './modules/cartes/pages/GestionCartes';
import { ImportCN } from './modules/cartes/pages/ImportCN';
import { ListeEntretiens } from './modules/entretien/pages/ListeEntretiens';
import { CarWash } from './modules/entretien/pages/CarWash';
import { Vehicules } from './modules/entretien/pages/Vehicules';
import { Services } from './modules/entretien/pages/Services';
import { Referentiels } from './modules/referentiels/pages/Referentiels';
import { RapportJournalier } from './modules/rapports/pages/RapportJournalier';
import { RapportMensuel } from './modules/rapports/pages/RapportMensuel';
import { SoldesClients } from './modules/rapports/pages/SoldesClients';
import { SoldesFournisseurs } from './modules/rapports/pages/SoldesFournisseurs';
import { Parametres } from './modules/parametres/pages/Parametres';
import { GestionUtilisateurs } from './modules/utilisateurs/pages/GestionUtilisateurs';
import { MonCompte } from './modules/utilisateurs/pages/MonCompte';
import { POSTerminal } from './modules/pos/pages/POSTerminal';
import './styles.css';

const queryClient = new QueryClient();
const theme = { token: { colorPrimary: '#d97706', colorInfo: '#d97706', borderRadius: 6, fontFamily: 'Manrope, sans-serif' } };
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={queryClient}><ConfigProvider theme={theme}><BrowserRouter><Routes><Route path="/login" element={<Login />} /><Route element={<ProtectedRoute />}><Route element={<AppLayout />}><Route path="/" element={<Dashboard />} /><Route path="/pos" element={<POSTerminal />} /><Route path="/carburant/releves" element={<RelevePompes />} /><Route path="/carburant/stock" element={<StockCuves />} /><Route path="/carburant/retours" element={<RetourCuve />} /><Route path="/carburant/inventaires" element={<InventaireCarburant />} /><Route path="/carburant/jaugeages" element={<Jaugeages />} /><Route path="/caisse/saisie" element={<SaisieCaisse />} /><Route path="/caisse/cloture" element={<ClotureCaisse />} /><Route path="/clients" element={<ListeClients />} /><Route path="/clients/bl" element={<SaisieBL />} /><Route path="/clients/factures" element={<ListeFactures />} /><Route path="/clients/impayes" element={<Impayes />} /><Route path="/fournisseurs" element={<ListeFournisseurs />} /><Route path="/fournisseurs/reglements" element={<ReglementFournisseur />} /><Route path="/fournisseurs/retenues" element={<RetenuesSource />} /><Route path="/fournisseurs/avoirs" element={<AvoirsFournisseurs />} /><Route path="/banque/mouvements" element={<MouvementsBancaires />} /><Route path="/banque/position" element={<PositionBanque />} /><Route path="/boutique/produits" element={<ListeProduits />} /><Route path="/boutique/achats" element={<AchatProduits />} /><Route path="/boutique/inventaire" element={<Inventaire />} /><Route path="/boutique/ventes" element={<VentesResume />} /><Route path="/cartes" element={<GestionCartes />} /><Route path="/cartes/import" element={<ImportCN />} /><Route path="/entretien" element={<ListeEntretiens />} /><Route path="/entretien/carwash" element={<CarWash />} /><Route path="/entretien/vehicules" element={<Vehicules />} /><Route path="/entretien/services" element={<Services />} /><Route path="/referentiels" element={<Referentiels />} /><Route path="/rapports/journalier" element={<RapportJournalier />} /><Route path="/rapports/mensuel" element={<RapportMensuel />} /><Route path="/rapports/clients" element={<SoldesClients />} /><Route path="/rapports/fournisseurs" element={<SoldesFournisseurs />} /><Route path="/systeme" element={<Parametres />} /><Route path="/utilisateurs" element={<GestionUtilisateurs />} /><Route path="/mon-compte" element={<MonCompte />} /><Route path="*" element={<Navigate to="/" replace />} /></Route></Route><Route path="*" element={<Navigate to="/login" replace />} /></Routes></BrowserRouter></ConfigProvider></QueryClientProvider></React.StrictMode>);
