import { useState } from 'react';
import dayjs, { type Dayjs } from 'dayjs';
import { Button, Card, Col, DatePicker, Form, InputNumber, Row, Select, Space, Table, Typography, message } from 'antd';
import { useClients, useCreateBonLivraison, useProduits, type Produit } from '../hooks/useClients';

interface Line { id: string; idProduit: number; puHT: number; tva: number; qte: number; remise: number; }
const lineTotal = (line: Line) => Math.max(0, line.puHT * line.qte - line.remise) * (1 + line.tva / 100);

export function SaisieBL() {
  const [date, setDate] = useState<Dayjs>(dayjs()); const [clientId, setClientId] = useState<number>(); const [lines, setLines] = useState<Line[]>([]); const [productId, setProductId] = useState<number>(); const [qte, setQte] = useState(1); const [puHT, setPuHT] = useState(0); const [tva, setTva] = useState(19); const [remise, setRemise] = useState(0); const [messageApi, holder] = message.useMessage();
  const { data: clients = [] } = useClients(); const { data: products = [] } = useProduits(); const create = useCreateBonLivraison();
  const selectedProduct = products.find((product) => product.id === productId);
  const addLine = () => { if (!productId || qte <= 0) { messageApi.warning('Selectionnez un produit et une quantite.'); return; } setLines((current) => [...current, { id: `${Date.now()}-${productId}`, idProduit: productId, puHT, tva, qte, remise }]); setProductId(undefined); setQte(1); setPuHT(0); setRemise(0); };
  const total = lines.reduce((sum, line) => sum + lineTotal(line), 0);
  const submit = async () => { if (!clientId || !lines.length) { messageApi.warning('Selectionnez un client et ajoutez au moins une ligne.'); return; } try { await create.mutateAsync({ date: date.format('YYYY-MM-DD'), clientId, lignes: lines.map(({ id: _id, ...line }) => line) }); setLines([]); messageApi.success('Bon de livraison cree.'); } catch (error: any) { messageApi.error(error?.response?.data?.message ?? 'Impossible de creer le bon.'); } };
  const productOptions = products.map((product: Produit) => ({ value: product.id, label: `${product.code} · ${product.libelle}` }));
  return <section className="page-section">{holder}<div className="page-heading"><div><Typography.Text className="eyebrow">CLIENTS / FACTURATION</Typography.Text><Typography.Title level={2}>Nouveau bon de livraison</Typography.Title></div><Typography.Text type="secondary">Ajoutez les articles puis contrôlez le TTC</Typography.Text></div><Card className="form-card"><Row gutter={16}><Col xs={24} md={8}><Typography.Text strong>Client</Typography.Text><Select style={{ width: '100%', marginTop: 8 }} value={clientId} onChange={setClientId} options={clients.map((client) => ({ value: client.id, label: client.nomClient }))} /></Col><Col xs={24} md={8}><Typography.Text strong>Date</Typography.Text><DatePicker style={{ width: '100%', marginTop: 8 }} value={date} onChange={(value) => value && setDate(value)} /></Col></Row></Card><Card title="Ligne article" className="form-card"><Space wrap><Select placeholder="Produit" value={productId} style={{ width: 240 }} onChange={(value) => { setProductId(value); const product = products.find((item) => item.id === value); if (product) { setPuHT(product.prixVenteHT); setTva(product.tva); } }} options={productOptions} /><InputNumber placeholder="Quantité" min={0.001} precision={3} value={qte} onChange={(value) => setQte(value ?? 0)} /><InputNumber placeholder="PU HT" min={0} precision={3} value={puHT} onChange={(value) => setPuHT(value ?? 0)} /><InputNumber placeholder="TVA %" min={0} precision={3} value={tva} onChange={(value) => setTva(value ?? 0)} /><InputNumber placeholder="Remise" min={0} precision={3} value={remise} onChange={(value) => setRemise(value ?? 0)} /><Button type="primary" onClick={addLine}>Ajouter</Button></Space>{selectedProduct && <Typography.Paragraph type="secondary">{selectedProduct.libelle} · TTC ligne: {lineTotal({ id: '', idProduit: selectedProduct.id, puHT, qte, tva, remise }).toFixed(3)} TND</Typography.Paragraph>}</Card><Card title={`Total TTC: ${total.toFixed(3)} TND`}><Table rowKey="id" pagination={false} dataSource={lines} columns={[{ title: 'Produit', render: (_, line) => products.find((product) => product.id === line.idProduit)?.libelle }, { title: 'Quantité', dataIndex: 'qte' }, { title: 'PU HT', dataIndex: 'puHT', render: (value) => value.toFixed(3) }, { title: 'TVA', dataIndex: 'tva', render: (value) => `${value}%` }, { title: 'TTC', render: (_, line) => lineTotal(line).toFixed(3) }, { title: 'Action', render: (_, line) => <Button danger size="small" onClick={() => setLines((current) => current.filter((item) => item.id !== line.id))}>Supprimer</Button> }]} /><Button type="primary" size="large" onClick={submit} loading={create.isPending} style={{ marginTop: 16 }}>Créer le bon de livraison</Button></Card></section>;
}
