import { useState } from 'react';
import dayjs, { type Dayjs } from 'dayjs';
import { Alert, Button, Card, Col, DatePicker, Form, Row, Select, Space, Statistic, Table, Typography, message } from 'antd';
import { useCaisses, useEquipes, useReleves } from '../../carburant/hooks/useCarburant';
import { useCaisseSummary, useCloturerCaisse, type CaisseContext } from '../hooks/useCaisse';

interface ClosureForm { date: Dayjs; equipeId: number; caisseId: number; }
const money = (value: number) => `${value.toFixed(3)} TND`;

export function ClotureCaisse() {
  const [form] = Form.useForm<ClosureForm>(); const [context, setContext] = useState<Pick<CaisseContext, 'date' | 'equipeId' | 'caisseId'>>({ date: dayjs().format('YYYY-MM-DD'), equipeId: 0, caisseId: 0 }); const [success, setSuccess] = useState(false); const [messageApi, holder] = message.useMessage();
  const { data: equipes = [] } = useEquipes(); const { data: caisses = [] } = useCaisses(); const { data: releves = [] } = useReleves(); const { data: summary } = useCaisseSummary(context); const closure = useCloturerCaisse();
  const updateContext = (values: Partial<ClosureForm>) => { const { date, ...rest } = values; setContext((current) => ({ ...current, ...rest, ...(date ? { date: date.format('YYYY-MM-DD') } : {}) })); };
  const submit = async () => { if (!context.equipeId || !context.caisseId) { messageApi.warning('Selectionnez une equipe et une caisse.'); return; } const ouverts = releves.filter((releve) => releve.date === context.date && releve.equipe.id === context.equipeId && releve.caisse.id === context.caisseId && releve.indexFermeture == null); if (ouverts.length) { messageApi.warning(`Fermez les pompes suivantes avant la cloture : ${ouverts.map((releve) => releve.pompe.code).join(', ')}.`); return; } try { await closure.mutateAsync({ date: context.date, equipeId: context.equipeId, caisseId: context.caisseId }); setSuccess(true); } catch (error: any) { messageApi.error(error?.response?.data?.message ?? 'Impossible de cloturer la caisse.'); } };
  const options = (items: Array<{ id: number; code?: string; libelle?: string }>) => items.map((item) => ({ value: item.id, label: `${item.code ?? ''}${item.code ? ' · ' : ''}${item.libelle ?? ''}` }));
  const net = summary?.soldeNet ?? 0;
  return <section className="page-section">{holder}<div className="page-heading"><div><Typography.Text className="eyebrow">CAISSE / CLÔTURE</Typography.Text><Typography.Title level={2}>Clôture de caisse</Typography.Title></div><Typography.Text type="secondary">Contrôlez les totaux avant de fermer la journée</Typography.Text></div><Card className="form-card"><Form form={form} layout="vertical" initialValues={{ date: dayjs() }} onValuesChange={updateContext}><Row gutter={16}><Col xs={24} md={8}><Form.Item label="Date" name="date"><DatePicker style={{ width: '100%' }} /></Form.Item></Col><Col xs={24} md={8}><Form.Item label="Equipe" name="equipeId"><Select options={options(equipes)} /></Form.Item></Col><Col xs={24} md={8}><Form.Item label="Caisse" name="caisseId"><Select options={options(caisses)} /></Form.Item></Col></Row></Form></Card>{success && <Alert message="Clôture enregistrée avec succès." type="success" showIcon closable onClose={() => setSuccess(false)} />}<Row gutter={[16, 16]} className="stat-row"><Col xs={24} sm={12} lg={6}><Card><Statistic title="Recettes" value={summary?.totalRecettes ?? 0} precision={3} suffix="TND" valueStyle={{ color: '#16803c' }} /></Card></Col><Col xs={24} sm={12} lg={6}><Card><Statistic title="Dépenses" value={summary?.totalDepenses ?? 0} precision={3} suffix="TND" valueStyle={{ color: '#cf1322' }} /></Card></Col><Col xs={24} sm={12} lg={6}><Card><Statistic title="Crédits" value={summary?.totalCredits ?? 0} precision={3} suffix="TND" valueStyle={{ color: '#d97706' }} /></Card></Col><Col xs={24} sm={12} lg={6}><Card><Statistic title="Solde net" value={net} precision={3} suffix="TND" valueStyle={{ color: net >= 0 ? '#16803c' : '#cf1322' }} /></Card></Col></Row><Card title="Recettes par mode de paiement" className="table-card"><Table rowKey="modePaymentId" pagination={false} dataSource={summary?.breakdown ?? []} columns={[{ title: 'Mode de paiement', dataIndex: 'libelle' }, { title: 'Montant', dataIndex: 'montant', render: (value) => money(value) }]} /></Card><Space><Button type="primary" danger disabled={!context.equipeId || !context.caisseId || summary?.fait || success} loading={closure.isPending} onClick={submit}>Confirmer la clôture</Button>{summary?.fait && <Typography.Text type="success">Journée déjà clôturée</Typography.Text>}</Space></section>;
}
